---
title: "Linear Models 3 (Lecture)"
output:
  html_document:
    df_print: paged
---

```{r}
library("knitr")      # for knitting RMarkdown 
library("janitor")    # for cleaning column names
library("broom")      # for tidying up linear models 
library("tidyverse")  # for wrangling, plotting, etc.
```


```{r}
#load data
#survey <- read.csv("survey.csv")  
data <- read.csv("data_rt_soa.csv") %>%
                  mutate(cue_type = factor(cue_type), soa = factor(soa))
```

## Step 2: Visualize Data
```{r}
# Histogram Reaction Time 
data %>%
  ggplot(mapping = aes(x = pc, fill = cue_type)) +
  geom_histogram()

#
data %>%
  ggplot(mapping = aes(x = pc,y = soa, fill = cue_type)) +
  geom_boxplot(notch = FALSE) +
  coord_flip() +
  xlab("Proportion Correct") +
  ylab("SOA (ms)") +
  scale_size_area("Cue Type")
```

## Step 3: Fit Models
Define and fit the compact model (Model C): $$Y_{i} = \beta_{0} + \epsilon_{i}$$
```{r}
# fit compact model
fit_compact = tidy(lm(TimeBed ~ 1, data = survey))
# plot the data with model prediction
ggplot(data = survey,
       aes(x = HourPhone, y = TimeBed)) + 
  geom_hline(yintercept = fit_compact$estimate,
             color = "red") +
  geom_point(size = 3) +
  xlab("Screen Time (hr)") + ylab("Bed Time (time)")
```
Define and fit the augmented model (Model A): $$Y_{i} = \beta_{0} + \beta_{1}X_{i}+ \epsilon_{i}$$
```{r}
# fit compact model
fit_augmented = tidy(lm(TimeBed ~ HourPhone, data = survey))
# plot the data with model prediction
ggplot(data = survey,
       aes(x = HourPhone, y = TimeBed)) + 
  geom_abline(intercept = fit_augmented$estimate[1],
              slope = fit_augmented$estimate[2],
              color = "blue") +
  geom_point(size = 3) +
  xlab("Screen Time (hr)") + ylab("Bed Time (time)")
summary(lm(TimeBed ~ HourPhone, data = survey))
```
```{r}
# pearson correlation
test <- cor.test(survey$HourPhone, survey$TimeBed)
```
## Step4: Compare Models
```{r}
# visualize residuals
lm.compact = lm(TimeBed ~ 1, data = survey)
# store the model information
df.compact_summary = tidy(lm.compact)

# plot model prediction with residuals
ggplot(data = augment(lm.compact),
       aes(x = survey$HourPhone,
           y = survey$TimeBed)) +
  geom_hline(yintercept = df.compact_summary$estimate,
             color = "red",
              size = 1) +
  geom_segment(aes(xend = survey$HourPhone,
                   yend = df.compact_summary$estimate),
               color = "red") + 
  xlab("Screen Time (hr)") + 
  ylab("BedTime (time)") +
  geom_point(size = 2) 

# plot histogram of residuals
ggplot(df.compact_model, aes(x=.resid)) + 
  geom_histogram(binwidth=.5) +
  xlab("Residual") +
  ylab("Frequency")
```
```{r}
# visualize residuals
lm.augmented = lm(TimeBed ~ HourPhone, data = survey)
# store the model information
df.augmented_summary = tidy(lm.augmented)
# create a data frame that contains the residuals
df.augmented_model = augment(lm.augmented) %>% 
  clean_names() #%>% 
  #left_join(survey, by = c("TimeBed", "HourPhone"))


# plot model prediction with residuals
ggplot(data = augment(lm.augmented),
       aes(x = HourPhone,
           y = TimeBed)) +
  geom_abline(intercept = df.augmented_summary$estimate[1],
              slope = df.augmented_summary$estimate[2],
             color = "blue",
              size = 1) +
  geom_segment(aes(xend = HourPhone,
              yend = .fitted),
               color = "blue") + 
  xlab("Screen Time (hr)") + 
  ylab("BedTime (time)") +
  geom_point(size = 2) 

# plot histogram of residuals
ggplot(df.augmented_model, aes(x=resid)) + 
  geom_histogram(binwidth=.25) +
  xlab("Residual") +
  ylab("Frequency")

# plot residual varies with x
ggplot(data = df.augmented_model,
       aes(x = hour_phone,
           y = resid)) + 
  geom_hline(yintercept = 0,
             color = "black",
              size = 1) +
  geom_point(size = 2) +
  ylab("Residual") +
  xlab("Screen Time (hr)")
```

```{r}
lm.compact <- lm(TimeBed ~ 1, data = survey)
df.compact_model = augment(lm.compact)
SSE_compact = sum(df.compact_model$.resid^2)
lm.augmented <- lm(TimeBed ~ HourPhone, data = survey)
df.augmented_model = augment(lm.augmented)
SSE_augmented = sum(df.augmented_model$.resid^2)
```


