---
title: "Linear Models 3 (Lecture)"
output:
  html_document:
    df_print: paged
---

```{r}
library("tidyverse")  # for wrangling, plotting, etc.
library("knitr")      # for knitting RMarkdown 
library("janitor")    # for cleaning column names
library("broom")      # for tidying up linear models 
theme_set(theme_bw() + #set the theme 
            theme(text = element_text(size = 16))) #set the default text size
```
## Generate dataset
```{r}
#population distribution
set.seed(124)
mu_cat = 50
sig_cat = 6
cat = rnorm(100,mu_cat,sig_cat)

mu_dog = 20
sig_dog = 6
dog = rnorm(100,mu_dog,sig_dog)

mu_hampster = 20
sig_hampster = 6
hampster = rnorm(100,mu_hampster,sig_hampster)

```

## Visualize dataset
```{r}
df<-tibble(cat, dog, hampster)
df<-pivot_longer(df, everything(), names_to = "pet", values_to = "beans")
ggplot(data = df,
       aes(x = pet, y = beans)) + 
  geom_point(alpha = 0.2,
             position = position_jitter(height = 0, width = 0.1)) +
  stat_summary(fun.data = "mean_cl_boot",
               geom = "linerange",
               size = 1) + 
  stat_summary(fun = "mean",
               geom = "point",
               shape = 21,
               size = 4) +
  labs(y = "Meowmeow beans")
```
## One-way ANOVA
```{r}
aov1<-aov(beans~factor(pet), df)
summary(aov1)
```
## Model fitting
```{r}
fit_c = lm(formula = beans ~ 1, data = df)
fit_a = lm(formula = beans ~ pet, data = df)

# plot compact
set.seed(1)
df.plot = df %>% 
  mutate(pet_jitter = 1 + runif(n(), min = -0.15, max = 0.15))

df.augment = fit_c %>% 
  augment() %>% 
  clean_names() %>% 
  bind_cols(df.plot %>% 
              select(pet, pet_jitter))

ggplot(data = df.plot, 
       mapping = aes(x = pet_jitter,
                     y = beans,
                     fill = pet)) + 
  geom_hline(yintercept = mean(df$beans)) +
  geom_point(alpha = 0.5) + 
  geom_segment(data = df.augment,
               mapping = aes(xend = pet_jitter,
                             yend = fitted),
               alpha = 0.2) +
  labs(y = "Meowmeow beans") + 
  theme(legend.position = "none",
        axis.text.x = element_blank(),
        axis.title.x = element_blank())
```

```{r}
# Plot augmented
set.seed(1)
df.plot = df %>% 
  mutate(pet_jitter = pet %>% 
           factor() %>%
           as.numeric(),
         pet_jitter = pet_jitter + runif(n(), min = -0.2, max = 0.2))

df.tidy = fit_a %>% 
  tidy() %>% 
  select(where(is.numeric)) %>% 
  mutate(across(.fns = ~ round(., digits = 2)))

df.augment = fit_a %>% 
  augment() %>%
  clean_names() %>% 
  bind_cols(df.plot %>% 
              select(pet_jitter))

ggplot(data = df.plot,
       mapping = aes(x = pet_jitter,
                     y = beans,
                     color = pet)) + 
  geom_point(alpha = 0.8) +
  geom_segment(data = NULL,
               mapping = aes(x = 0.6,
                             xend = 1.4,
                             y = df.tidy$estimate[1],
                             yend = df.tidy$estimate[1]),
               color = "lightpink",
               size = 1) +
  geom_segment(data = NULL,
               aes(x = 1.6,
                   xend = 2.4,
                   y = df.tidy$estimate[1] + df.tidy$estimate[2],
                   yend = df.tidy$estimate[1] + df.tidy$estimate[2]),
               color = "lightblue",
               size = 1) +
  geom_segment(data = NULL,
               aes(x = 2.6,
                   xend = 3.4,
                   y = df.tidy$estimate[1] + df.tidy$estimate[3],
                   yend = df.tidy$estimate[1] + df.tidy$estimate[3]),
               color = "peachpuff",
               size = 1) +
  geom_segment(data = df.augment,
               aes(xend = pet_jitter,
                   y = beans,
                   yend = fitted),
               alpha = 0.3) +
  labs(y = "Meowmeow beans") + 
  scale_color_manual(values = c("lightpink", "lightblue", "peachpuff")) + 
  scale_x_continuous(breaks = 1:3, labels = c("cat", "dog", "hampster")) + 
  theme(legend.position = "none",
        axis.title.x = element_blank())
```